name: tagllm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy=1.21.2
  - pandas=1.5.3
  - pydantic=1.10.12
  - pip:
    - accelerate==0.23.0
    - datasets==2.17.1
    - deepspeed==0.8.3
    - evaluate==0.3.0
    - fire==0.5.0
    - hydra-core==1.2.0
    - omegaconf>=2.1.1
    - openai==0.27.2
    - rouge_score==0.1.2
    - nltk==3.6.2
    - sentencepiece==0.1.98
    - torch==2.0.0
    - wandb==0.13.4
    - PyTDC==0.4.1
    - peptides==0.3.2
    - peft==0.5.0
    - git+https://github.com/huggingface/transformers@fb366b9a
    - opencc-python-reimplemented==0.1.7
