name: tagllm-new
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - pydantic
  - pip:
    - accelerate
    - datasets
    - deepspeed
    - evaluate
    - fire
    - hydra-core
    - omegaconf
    - openai
    - rouge_score
    - nltk
    - sentencepiece
    - torch
    - wandb
    - PyTDC
    - peptides
    - peft
    - transformers
    - opencc-python-reimplemented
